export const COBRADE_LIST = [
    { code: '1.1.1.1.0', name: 'Naturais - Geológicos - Terremoto - Tremor de terra' },
    { code: '1.1.1.2.0', name: 'Naturais - Geológicos - Terremoto - Tsunami' },
    { code: '1.1.2.0.0', name: 'Naturais - Geológicos - Emanação vulcânica' },
    { code: '1.1.3.1.1', name: 'Naturais - Geológicos - Movimento de massa - Quedas - Blocos' },
    { code: '1.1.3.1.2', name: 'Naturais - Geológicos - Movimento de massa - Quedas - Lascas' },
    { code: '1.1.3.1.3', name: 'Naturais - Geológicos - Movimento de massa - Quedas - Matacões' },
    { code: '1.1.3.1.4', name: 'Naturais - Geológicos - Movimento de massa - Quedas - Lajes' },
    { code: '1.1.3.2.1', name: 'Naturais - Geológicos - Movimento de massa - Deslizamentos de solo e/ou rocha' },
    { code: '1.1.3.3.1', name: 'Naturais - Geológicos - Movimento de massa - Corridas de Massa - Solo/Lama' },
    { code: '1.1.3.3.2', name: 'Naturais - Geológicos - Movimento de massa - Corridas de Massa - Rocha/Detrito' },
    { code: '1.1.3.4.0', name: 'Naturais - Geológicos - Movimento de massa - Subsidências e colapsos' },
    { code: '1.1.4.1.0', name: 'Naturais - Geológicos - Erosão Costeira/Marinha' },
    { code: '1.1.4.2.0', name: 'Naturais - Geológicos - Erosão de Margem Fluvial' },
    { code: '1.1.4.3.1', name: 'Naturais - Geológicos - Erosão Continental - Laminar' },
    { code: '1.1.4.3.2', name: 'Naturais - Geológicos - Erosão Continental - Ravinas' },
    { code: '1.1.4.3.3', name: 'Naturais - Geológicos - Erosão Continental - Boçorocas' },
    { code: '1.2.1.0.0', name: 'Naturais - Hidrológicos - Inundações' },
    { code: '1.2.2.0.0', name: 'Naturais - Hidrológicos - Enxurradas' },
    { code: '1.2.3.0.0', name: 'Naturais - Hidrológicos - Alagamentos' },
    { code: '1.3.1.1.1', name: 'Naturais - Meteorológicos - Ciclones - Ventos Costeiros' },
    { code: '1.3.1.1.2', name: 'Naturais - Meteorológicos - Ciclones - Marés de Tempestade' },
    { code: '1.3.1.2.0', name: 'Naturais - Meteorológicos - Frentes Frias/Zonas de Convergência' },
    { code: '1.3.2.1.1', name: 'Naturais - Meteorológicos - Tempestades - Tornados' },
    { code: '1.3.2.1.2', name: 'Naturais - Meteorológicos - Tempestades - Tempestade de Raios' },
    { code: '1.3.2.1.3', name: 'Naturais - Meteorológicos - Tempestades - Granizo' },
    { code: '1.3.2.1.4', name: 'Naturais - Meteorológicos - Tempestades - Chuvas Intensas' },
    { code: '1.3.2.1.5', name: 'Naturais - Meteorológicos - Tempestades - Vendaval' },
    { code: '1.3.3.1.0', name: 'Naturais - Meteorológicos - Temperaturas Extremas - Onda de Calor' },
    { code: '1.3.3.2.1', name: 'Naturais - Meteorológicos - Temperaturas Extremas - Onda de Frio - Friagem' },
    { code: '1.3.3.2.2', name: 'Naturais - Meteorológicos - Temperaturas Extremas - Onda de Frio - Geadas' },
    { code: '1.4.1.1.0', name: 'Naturais - Climatológicos - Seca - Estiagem' },
    { code: '1.4.1.2.0', name: 'Naturais - Climatológicos - Seca - Seca' },
    { code: '1.4.1.3.1', name: 'Naturais - Climatológicos - Incêndio Florestal em Áreas Protegidas' },
    { code: '1.4.1.3.2', name: 'Naturais - Climatológicos - Incêndio Florestal em Áreas Não Protegidas' },
    { code: '1.4.1.4.0', name: 'Naturais - Climatológicos - Baixa Umidade do Ar' },
    { code: '1.5.1.1.0', name: 'Naturais - Biológicos - Epidemias - Doenças infecciosas virais' },
    { code: '1.5.1.2.0', name: 'Naturais - Biológicos - Epidemias - Doenças infecciosas bacterianas' },
    { code: '1.5.1.3.0', name: 'Naturais - Biológicos - Epidemias - Doenças infecciosas parasíticas' },
    { code: '1.5.1.4.0', name: 'Naturais - Biológicos - Epidemias - Doenças infecciosas fúngicas' },
    { code: '1.5.2.1.0', name: 'Naturais - Biológicos - Infestações de animais' },
    { code: '1.5.2.2.1', name: 'Naturais - Biológicos - Infestações de algas - Marés vermelhas' },
    { code: '1.5.2.2.2', name: 'Naturais - Biológicos - Infestações de algas - Cianobactérias' },
    { code: '2.1.1.1.0', name: 'Tecnológicos - Radioativos - Queda de satélite' },
    { code: '2.1.2.1.1', name: 'Tecnológicos - Radioativos - Acidentes em instalações de saúde' },
    { code: '2.1.2.1.2', name: 'Tecnológicos - Radioativos - Acidentes em instalações industriais' },
    { code: '2.1.2.2.0', name: 'Tecnológicos - Radioativos - Liberação de radionuclídeos' },
    { code: '2.2.1.1.0', name: 'Tecnológicos - Produtos Perigosos - Liberação de produtos químicos' },
    { code: '2.2.2.1.0', name: 'Tecnológicos - Produtos Perigosos - Acidentes rodoviários' },
    { code: '2.2.2.2.0', name: 'Tecnológicos - Produtos Perigosos - Derramamento em ambiente aquático' },
    { code: '2.2.2.3.0', name: 'Tecnológicos - Produtos Perigosos - Vazamento em oleodutos/gasodutos' },
    { code: '2.3.1.1.0', name: 'Tecnológicos - Incêndios Urbanos - Instalações industriais/depósitos' },
    { code: '2.3.2.1.0', name: 'Tecnológicos - Incêndios Urbanos - Aglomerados residenciais' },
    { code: '2.3.3.1.0', name: 'Tecnológicos - Incêndios Urbanos - Edificações comerciais' },
    { code: '2.4.1.1.0', name: 'Tecnológicos - Obras Civis - Colapso de edificações' },
    { code: '2.4.1.3.0', name: 'Tecnológicos - Obras Civis - Colapso de barragens' },
    { code: '2.4.2.1.0', name: 'Tecnológicos - Obras Civis - Falha de abastecimento de água' },
    { code: '2.4.2.3.0', name: 'Tecnológicos - Obras Civis - Falha de energia elétrica' },
    { code: '2.5.1.1.0', name: 'Tecnológicos - Transporte - Acidentes ferroviários' },
    { code: '2.5.1.2.0', name: 'Tecnológicos - Transporte - Acidentes rodoviários' },
    { code: '2.5.2.1.0', name: 'Tecnológicos - Transporte - Queda de aeronaves' },
    { code: '2.5.3.1.0', name: 'Tecnológicos - Transporte - Naufrágios' },
];
