-- ===================================================================
-- DATABASE MIGRATION: SIGERD S2ID & CONECTA ESTADUAL
-- This script creates the necessary tables for both the municipal
-- records and the state-level control decisions.
-- ===================================================================

-- 1. Create S2ID Records table (Municipal Data)
-- This table is populated by municipalities via SIGERD Mobile.
CREATE TABLE IF NOT EXISTS public.s2id_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s2id_id UUID UNIQUE DEFAULT gen_random_uuid(),
    id_local TEXT,
    status TEXT DEFAULT 'draft',
    data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create State Control table (Conecta Estadual Data)
-- This table stores state-level analysis for each municipal occurrence.
-- Tabela para Controle Estadual de Solicitações (S2ID + Ocorrências)
CREATE TABLE IF NOT EXISTS public.estado_controle (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    s2id_id text UNIQUE, -- Pode ser UUID do S2ID ou da Ocorrência
    status_estadual text DEFAULT 'Em análise',
    notas text,
    analista text, -- Quem realizou o despacho
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Tabela para Ocorrências Operacionais (Dados rápidos do campo)
CREATE TABLE IF NOT EXISTS public.ocorrencias_operacionais (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    id_local integer,
    ocorrencia_id text UNIQUE,
    municipio text DEFAULT 'Santa Maria de Jetibá',
    tipo text, -- Denominação COBRADE
    cobrade text,
    data_ocorrencia text,
    horario_ocorrencia text,
    lat double precision,
    lng double precision,
    accuracy double precision,
    mortos integer DEFAULT 0,
    feridos integer DEFAULT 0,
    enfermos integer DEFAULT 0,
    desalojados integer DEFAULT 0,
    desabrigados integer DEFAULT 0,
    desaparecidos integer DEFAULT 0,
    outros_afetados integer DEFAULT 0,
    descricao_danos text,
    observacoes text,
    status text DEFAULT 'finalized',
    usuario text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. Enable Realtime for all tables
-- This ensures the dashboard updates instantly when data changes.
-- Note: You might need to check if 'supabase_realtime' publication exists.
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.s2id_records;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.estado_controle;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ocorrencias_operacionais;
  END IF;
END $$;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.s2id_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_controle ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Permissive for production setup - adjust as needed)

-- Municipal Records Policies
CREATE POLICY "Enable all for authenticated users" ON public.s2id_records
    FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for public" ON public.s2id_records
    FOR SELECT USING (true);

-- State Control Policies
CREATE POLICY "Enable all for authenticated analysts" ON public.estado_controle
    FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable read for public analysts" ON public.estado_controle
    FOR SELECT USING (true);

-- 6. Comments
COMMENT ON TABLE public.s2id_records IS 'Stores municipal S2ID occurrence records.';
COMMENT ON TABLE public.estado_controle IS 'Stores Conecta Estadual analysis for S2ID records.';
